const { __ } = wp.i18n;
import icons from '../Icons';

import Checkbox from '../../blocks/types/checkbox';
import ColorSwatches from '../../blocks/types/color_swatches';
import ImageSwatches from '../../blocks/types/img_swatches';
import Radio from '../../blocks/types/radio';
import Select from '../../blocks/types/select';
import Switcher from '../../blocks/types/switcher';

import Color from '../../blocks/types/color';
import Number from '../../blocks/types/number';
import Upload from '../../blocks/types/upload';

import Date from '../../blocks/types/date';
import Time from '../../blocks/types/time';

import Range from '../../blocks/types/range';
import TextArea from '../../blocks/types/text_area';
import Url from '../../blocks/types/url';

import Heading from '../../blocks/types/heading';
import Shortcode from '../../blocks/types/shortcode';
import Spacer from '../../blocks/types/spacer';

import Email from '../../blocks/types/email';

import Button from '../../blocks/types/button';
import Content from '../../blocks/types/content';
import CustomFormula from '../../blocks/types/custom_formula';
import DateTime from '../../blocks/types/datetime';
import FontPicker from '../../blocks/types/font_picker';
import PopUp from '../../blocks/types/popup';
import Products from '../../blocks/types/products';
import Section from '../../blocks/types/section';
import Separator from '../../blocks/types/seperator';
import Telephone from '../../blocks/types/telephone';
import TextField from '../../blocks/types/text_field';
import { generateUID } from '../Utils';

const pradAllBlocks = {
	section: {
		name: 'Section',
		keyWords: [ 'container', 'inner', 'blocks' ],
		priority: 1,
		icon: icons.section,
		com: Section,
		def: {
			label: 'Section Container',
			class: '',
			id: '',
			hide: false,
			required: false,
			showAccordion: false,
			innerBlocks: [],
		},
	},
	radio: {
		name: 'Radio',
		keyWords: [ 'radio', 'select', 'choice', 'option', 'single' ],
		priority: 2,
		icon: icons.radio,
		com: Radio,
		def: {
			label: 'Radio Field',
			desc: '',
			columns: '1',
			enableCount: false,
			hide: false,
			required: false,
			min: 1,
			max: 100,
			pricePosition: 'with_option',
			imgStyle: 'normal',
			_options: [
				{
					value: 'Option 1',
					type: 'fixed',
					regular: '8',
					sale: '',
					def: false,
					uid: generateUID(),
				},
				{
					value: 'Option 2',
					type: 'fixed',
					regular: '6',
					sale: '',
					def: false,
					uid: generateUID(),
				},
				{
					value: 'Option 3',
					type: 'percentage',
					regular: '20',
					sale: '',
					def: false,
					uid: generateUID(),
				},
			],
			en_logic: false,
			fieldConditions: [],
		},
	},
	checkbox: {
		name: 'Checkbox',
		keyWords: [
			'checkbox',
			'check',
			'multiple',
			'choice',
			'option',
			'tick',
		],
		priority: 10,
		icon: icons.checkbox,
		com: Checkbox,
		def: {
			label: 'Checkbox Field',
			desc: '',
			columns: '1',
			enableCount: false,
			hide: false,
			required: false,
			min: 1,
			max: 100,
			minSelect: '',
			maxSelect: '',
			pricePosition: 'with_option',
			imgStyle: 'normal',
			_options: [
				{
					value: 'Option 1',
					type: 'fixed',
					regular: '5',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Option 2',
					type: 'fixed',
					regular: '3',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Option 3',
					type: 'percentage',
					regular: '15',
					sale: '',
					uid: generateUID(),
				},
			],
			class: '',
			id: '',
		},
	},
	custom_formula: {
		name: 'Formula',
		keyWords: [
			'formula',
			'calculation',
			'math',
			'compute',
			'expression',
			'custom',
		],
		priority: 180,
		icon: icons.customFormula,
		com: CustomFormula,
		def: {
			formulaData: {},
			label: 'Formula Field',
		},
	},
	switch: {
		name: 'Switch',
		keyWords: [ 'switch', 'toggle', 'on', 'off', 'boolean', 'yes', 'no' ],
		priority: 20,
		icon: icons.switch,
		com: Switcher,
		def: {
			label: 'Switch Field',
			desc: '',
			enableCount: false,
			hide: false,
			required: false,
			min: 1,
			max: 100,
			pricePosition: 'with_option',
			imgStyle: 'normal',
			_options: [
				{
					value: 'Toggle Switch',
					type: 'fixed',
					regular: '7',
					sale: '',
					uid: generateUID(),
				},
			],
			class: '',
			id: '',
		},
	},
	select: {
		name: 'Select',
		keyWords: [ 'dropdown', 'select', 'list', 'options', 'choice', 'menu' ],
		priority: 30,
		icon: icons.select,
		com: Select,
		def: {
			label: 'Select Field',
			desc: '',
			hide: false,
			required: false,
			imgStyle: 'normal',
			_options: [
				{
					value: 'Option 1',
					type: 'fixed',
					regular: '8',
					sale: '',
					def: false,
					uid: generateUID(),
				},
				{
					value: 'Option 2',
					type: 'fixed',
					regular: '6',
					sale: '',
					def: false,
					uid: generateUID(),
				},
				{
					value: 'Option 3',
					type: 'percentage',
					regular: '12',
					sale: '',
					def: false,
					uid: generateUID(),
				},
			],
			class: '',
			id: '',
		},
	},
	font_picker: {
		name: 'Font Picker',
		keyWords: [ 'font', 'custom', 'picker', 'family' ],
		priority: 230,
		icon: icons.font_picker,
		isPro: ! pradBackendData.isActive || false,
		com: FontPicker,
		def: {
			label: 'Font Picker Field',
			class: '',
			id: '',
			hide: false,
			required: false,
			_options: [],
		},
	},
	products: {
		name: 'Products',
		keyWords: [
			'products',
			'items',
			'catalog',
			'shop',
			'woocommerce',
			'variations',
		],
		priority: 35,
		icon: icons.products,
		com: Products,
		def: {
			label: 'Products Field',
			layout: '_default',
			blockType: '_swatches',
			layoutVisibility: 'always_show',
			desc: '',
			multiple: false,
			hide: false,
			required: false,
			columns: '1',
			enableCount: false,
			mergeVarition: false,
			min: 1,
			max: 100,
			productType: '_manual_products',
			manualProducts: [],
			imgStyle: 'normal',
			_styles: {
				height: { val: '' },
				width: { val: '' },
				radius: { val: '' },
				_ovr_color: '#ffffff',
				_ovr_bg: '#0B0E04CC',
				mrR: { val: 8 },
			},
		},
	},
	upload: {
		name: 'Upload',
		keyWords: [
			'upload',
			'file',
			'attachment',
			'image',
			'document',
			'media',
		],
		priority: 40,
		icon: icons.upload,
		com: Upload,
		def: {
			label: 'Upload Field',
			placeholder: 'Drag &  Upload File',
			_options: [ { type: 'fixed', regular: '12', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
			maxSize: 2,
			sizePrefix: 'Max File Size: [max_size]',
			sizeError: 'File is too large',
			maxNumber: 3,
			numberPrefix: 'Maximum Number of Files: [max_files]',
			numberError: 'Too many files',
			allowedFileTypes: [ 'png', 'jpg' ],
			allowedPrefix: 'Allowed Types are: [allowed_types]',
		},
	},
	button: {
		name: 'Button',
		keyWords: [ 'button', 'groups' ],
		priority: 50,
		icon: icons.button,
		com: Button,
		def: {
			label: 'Button Field',
			desc: '',
			multiple: false,
			hide: false,
			required: false,
			vertical: false,
			_options: [
				{
					value: 'Button 1',
					type: 'fixed',
					regular: '8',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Button 2',
					type: 'fixed',
					regular: '6',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Button 3',
					type: 'fixed',
					regular: '3',
					sale: '',
					uid: generateUID(),
				},
			],
			class: '',
			id: '',
		},
	},
	img_switch: {
		name: 'Image Swatches',
		keyWords: [ 'image', 'swatches', 'visual', 'picture', 'thumbnail' ],
		icon: icons.imageSwatch,
		priority: 60,
		com: ImageSwatches,
		def: {
			label: 'Image Swatches',
			layout: '_default',
			layoutVisibility: 'always_show',
			desc: '',
			multiple: false,
			hide: false,
			required: false,
			enableCount: false,
			updateProductImage: false,
			min: 1,
			max: 100,
			_styles: {
				height: { val: '' },
				width: { val: '' },
				radius: { val: '' },
				_ovr_color: '#ffffff',
				_ovr_bg: '#0B0E04CC',
			},
			_options: [
				{
					value: 'Image #1',
					img: '',
					type: 'fixed',
					regular: '9',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Image #2',
					img: '',
					type: 'fixed',
					regular: '6',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Image #3',
					img: '',
					type: 'fixed',
					regular: '4',
					sale: '',
					uid: generateUID(),
				},
			],
			class: '',
			id: '',
		},
	},
	color_switch: {
		name: 'Color Swatches',
		keyWords: [ 'color', 'swatches', 'visual' ],
		priority: 70,
		icon: icons.colorSwatch,
		com: ColorSwatches,
		def: {
			label: 'Color Swatches',
			layout: '_default',
			layoutVisibility: 'always_show',
			desc: '',
			multiple: false,
			enableCount: false,
			hide: false,
			required: false,
			min: 1,
			max: 100,
			_styles: {
				height: { val: '' },
				width: { val: '' },
				radius: { val: '' },
				_ovr_color: '#ffffff',
				_ovr_bg: '#0B0E04CC',
			},
			_options: [
				{
					value: 'Color 1',
					color: '#EB9419',
					type: 'fixed',
					regular: '9',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Color 2',
					color: '#2C6BA6',
					type: 'fixed',
					regular: '6',
					sale: '',
					uid: generateUID(),
				},
				{
					value: 'Color 3',
					color: '#56B8B1',
					type: 'fixed',
					regular: '3',
					sale: '',
					uid: generateUID(),
				},
			],
			class: '',
			id: '',
		},
	},
	color_picker: {
		name: 'Color Picker',
		keyWords: [ 'color', 'picker' ],
		priority: 80,
		icon: icons.colorPicker,
		com: Color,
		def: {
			label: 'Color Picker',
			value: '#f43089',
			defaultColor: '#049845',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '4', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},

	datetime: {
		name: 'Date & Time',
		keyWords: [ 'date', 'datetime', 'calendar', 'day', 'month', 'time' ],
		priority: 90,
		icon: icons.dateTime,
		com: DateTime,
		def: {
			label: 'Date & Time Field',
			pricePosition: 'with_title',
			blockType: 'datetime',
			_options: [ { type: 'fixed', regular: '5', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
			timeFormat: '12_hours',
			dateFormat: 'DD/MM/YYYY',
			disableDays: [], // Sunday = 0
			disableDates: [],
			disableSpecificDates: [],
			maxTime: '',
			minTime: '',
			maxDateType: 'none',
			minDateType: 'none',
			maxDate: '',
			minDate: '',
		},
	},
	date: {
		name: 'Date',
		keyWords: [ 'date', 'calendar', 'day', 'month' ],
		priority: 90,
		icon: icons.date,
		com: Date,
		deprecated: true,
		def: {
			label: 'Date Field',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '5', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
			dateFormat: 'DD/MM/YYYY',
			disableDays: [], // Sunday = 0
			disableDates: [],
		},
	},
	time: {
		name: 'Time',
		keyWords: [ 'time', 'clock', 'timing' ],
		priority: 100,
		icon: icons.dateTime,
		com: Time,
		deprecated: true,
		def: {
			label: 'Time Field',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '4', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
			maxTime: '',
			minTime: '',
		},
	},
	range: {
		name: 'Range Slider',
		keyWords: [ 'range', 'slider' ],
		priority: 110,
		icon: icons.range,
		com: Range,
		def: {
			label: 'Range Field',
			_options: [ { type: 'per_unit', regular: '2', sale: '' } ],
			min: 1,
			max: 100,
			value: 10,
			step: 1,
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},
	url: {
		name: 'URL / Link',
		keyWords: [ 'url', 'link' ],
		priority: 120,
		icon: icons.url,
		com: Url,
		def: {
			label: 'URL / Link Field',
			placeholder: 'https://wpxpo.com',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '3', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},
	email: {
		name: 'Email',
		keyWords: [ 'email', 'mail' ],
		priority: 130,
		icon: icons.email,
		com: Email,
		def: {
			label: 'Email Field',
			placeholder: 'xyz@gmail.com',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '3', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},
	number: {
		name: 'Number',
		keyWords: [
			'number',
			'numeric',
			'integer',
			'decimal',
			'quantity',
			'amount',
		],
		priority: 140,
		icon: icons.number,
		com: Number,
		def: {
			label: 'Number Field',
			placeholder: 'Insert Number',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '3', sale: '' } ],
			min: 1,
			max: 100,
			step: 1,
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},
	telephone: {
		name: 'Telephone',
		keyWords: [
			'telephone',
			'phone',
			'mobile',
			'call',
			'number',
			'contact',
			'dial',
		],
		priority: 150,
		icon: icons.telephone,
		com: Telephone,
		def: {
			label: 'Telephone Field',
			placeholder: 'XXXXXXXXXX',
			flagStyle: 'number_only',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '2', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},
	textfield: {
		name: 'Text Field',
		keyWords: [ 'text', 'field', 'input', 'string', 'write', 'type' ],
		priority: 160,
		icon: icons.textfield,
		com: TextField,
		def: {
			label: 'Text Field',
			placeholder: 'Write Something...',
			pricePosition: 'with_title',
			_options: [ { type: 'fixed', regular: '2', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
		},
	},
	textarea: {
		name: 'Text Area',
		keyWords: [ 'textarea', 'text', 'area' ],
		priority: 160,
		icon: icons.textarea,
		com: TextArea,
		def: {
			label: 'Text Area',
			placeholder: 'Write from here...',
			_options: [ { type: 'fixed', regular: '2', sale: '' } ],
			class: '',
			id: '',
			hide: false,
			required: false,
			min: 24,
			max: 50,
			step: 5,
		},
	},
	content: {
		name: 'Content',
		keyWords: [ 'content', 'html' ],
		priority: 210,
		icon: icons.content,
		com: Content,
		def: {
			class: '',
			id: '',
			previewContent:
				'Lorem ipsum dolor sit amet consectetur adipiscing elit. Consectetur adipiscing elit quisque faucibus ex sapien vitae. Ex sapien vitae pellentesque sem placerat in id. Placerat in id cursus mi pretium tellus duis. Pretium tellus duis convallis tempus leo eu aenean.',
		},
	},
	popup: {
		name: 'Popup',
		keyWords: [ 'pop', 'up', 'modal' ],
		priority: 220,
		icon: icons.popup,
		com: PopUp,
		def: {
			label: 'Popup Field',
			class: '',
			id: '',
			hide: false,
			popupContent:
				'Lorem ipsum dolor sit amet consectetur adipiscing elit. Consectetur adipiscing elit quisque faucibus ex sapien vitae. Ex sapien vitae pellentesque sem placerat in id. Placerat in id cursus mi pretium tellus duis. Pretium tellus duis convallis tempus leo eu aenean.',
		},
	},
	heading: {
		name: 'Heading',
		keyWords: [ 'heading', 'title', 'h1', 'h2', 'h3', 'header' ],
		priority: 170,
		icon: icons.heading,
		com: Heading,
		deprecated: true,
		def: {
			value: 'Heading Example',
			tag: 'h1',
			hide: false,
			required: false,
		},
	},
	shortcode: {
		name: 'Shortcode',
		keyWords: [ 'shortcode', 'code' ],
		priority: 190,
		icon: icons.shortcode,
		com: Shortcode,
		def: {
			label: 'Shortcode',
			value: '',
			hide: false,
			required: false,
		},
	},
	separator: {
		name: 'Separator',
		keyWords: [ 'separator', 'divider', 'line', 'break', 'border' ],
		priority: 200,
		icon: icons.separator,
		com: Separator,
		def: {
			height: { val: '2', unit: 'px' },
			width: { val: '100', unit: '%' },
			separator_color: '#000fff',
			class: '',
			id: '',
			hide: false,
			required: false,
			_style: {
				_l_toolbar: {
					color: '#000',
				},
			},
		},
	},
	spacer: {
		name: 'Spacer',
		keyWords: [ 'spacer', 'space', 'gap', 'margin', 'padding', 'empty' ],
		priority: 210,
		icon: icons.spacer,
		com: Spacer,
		def: {
			height: { val: '40', unit: 'px' },
			class: '',
			id: '',
			hide: false,
			required: false,
			_style: {
				_l_toolbar: {
					height: { val: '20', unit: 'px' },
					color: '#fff',
				},
			},
		},
	},
};
const helpMenu = [
	{
		label: __( 'Get Support', 'product-addons' ),
		icon: 'dashicons-phone',
		link: 'https://www.wpxpo.com/contact/',
	},
	{
		label: __( 'Join Community', 'product-addons' ),
		icon: 'dashicons-facebook-alt',
		link: 'https://www.facebook.com/groups/wowcommercecommunity',
	},
	{
		label: __( 'YouTube Tutorials', 'product-addons' ),
		icon: 'dashicons-youtube',
		link: 'https://www.youtube.com/@wpxpo',
	},
	{
		label: __( 'Documentation', 'product-addons' ),
		icon: 'dashicons-book',
		link: '#',
	},
];
const iniGlobalStyle = {
	appliedStyle: 'style',
	common: {
		heading: {
			open: false,
			typo: {
				_size: { val: 18, unit: 'px' },
				_height: { val: 24, unit: 'px' },
				_space: { val: 1.2, unit: 'px' },
				_weight: '500',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#0B0E04',
		},
		title: {
			open: false,
			typo: {
				_size: { val: 16, unit: 'px' },
				_height: { val: 24, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '500',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#0B0E04',
		},
		description: {
			open: false,
			typo: {
				_size: { val: 14, unit: 'px' },
				_height: { val: 18, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '500',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#4e5049',
		},
		content: {
			open: false,
			typo: {
				_size: { val: 14, unit: 'px' },
				_height: { val: 20, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '400',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#192217',
		},
		placeHolder: {
			open: false,
			typo: {
				_size: { val: 14, unit: 'px' },
				_height: { val: 20, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '400',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#9FA79D',
		},
		price: {
			open: false,
			typo: {
				_size: { val: 14, unit: 'px' },
				_height: { val: 20, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '400',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#575E55',
		},
		sectionTitle: {
			open: false,
			typo: {
				_size: { val: 16, unit: 'px' },
				_height: { val: 24, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '500',
				_style: 'normal',
				_decoration: 'none',
			},
			color: '#0B0E04',
		},
	},
	field_comp: {
		section: {
			open: false,
			settings: {
				paddingTB: { val: 12, unit: 'px' },
				paddingLR: { val: 16, unit: 'px' },
				border: { val: 1, unit: 'px' },
				radius: { val: 4, unit: 'px' },
			},
			border_color: '#9FA79D',
			bg_color: '#ffffff',
		},
		input_field: {
			open: false,
			settings: {
				paddingTB: { val: 10, unit: 'px' },
				paddingLR: { val: 16, unit: 'px' },
				border: { val: 1, unit: 'px' },
				radius: { val: 4, unit: 'px' },
			},
			border_color: { normal: '#9FA79D', hover: '#0B0E04' },
			bg_color: { normal: '#ffffff', hover: '#ffffff' },
		},
		range: {
			open: false,
			settings: {
				height: { val: 8, unit: 'px' },
			},
			active_color: '#0b0e04',
			inactive_color: '#D5DAD4',
		},
		checkbox: {
			open: false,
			settings: {
				size: { val: 16, unit: 'px' },
				border: { val: 1, unit: 'px' },
				radius: { val: 2, unit: 'px' },
			},
			border_color: { normal: '#9FA79D', active: '#0b0e04' },
			bg_color: { normal: '#00000000', active: '#0b0e04' },
			icon_color: '#ffffff',
		},
		radio: {
			open: false,
			settings: {
				size: { val: 16, unit: 'px' },
				border: { val: 2, unit: 'px' },
			},
			// border_color: { normal: '#A1A1A1', hover: '#86A62C' },
			border_color: '#A1A1A1',
			bg_color: '#00000000',
			dot_color: '#0b0e04',
		},
		button: {
			open: false,
			settings: {
				paddingTB: { val: 10, unit: 'px' },
				paddingLR: { val: 16, unit: 'px' },
				border: { val: 1, unit: 'px' },
				radius: { val: 20, unit: 'px' },
			},
			typo: {
				_size: { val: 14, unit: 'px' },
				_height: { val: 20, unit: 'px' },
				_space: { val: 0, unit: 'px' },
				_weight: '400',
				_style: 'normal',
				_decoration: 'none',
			},
			color: { normal: '#0B0E04', hover: '#FFFFFF' },
			border_color: { normal: '#9FA79D', hover: '#192217' },
			bg_color: { normal: '#ffffff', hover: '#192217' },
		},
		switch: {
			open: false,
			settings: {
				size: { val: 40, unit: 'px' },
				border: { val: 0, unit: 'px' },
			},
			border_color: { normal: '#9FA79D', active: '#0b0e04' },
			bg_color: { normal: '#9FA79D', active: '#0b0e04' },
			thumb_color: '#ffffff',
		},
		swatches: {
			open: false,
			settings: {
				height: { val: 85, unit: 'px' },
				width: { val: 100, unit: 'px' },
				border: { val: 2, unit: 'px' },
				radius: { val: 4, unit: 'px' },
			},
			border_color: '#00000000',
			active_border_color: '#0b0e04',
		},
		color_swatches: {
			open: false,
			settings: {
				height: { val: 85, unit: 'px' },
				width: { val: 100, unit: 'px' },
				border: { val: 2, unit: 'px' },
				radius: { val: 4, unit: 'px' },
			},
			border_color: '#000000',
			active_border_color: '#0b0e04',
		},
		others: {
			open: false,
			separator_color: '#9FA79D',
			req_color: '#DF1C41',
			error_color: '#ff0101',
		},
	},
};

export { helpMenu, iniGlobalStyle, pradAllBlocks };
